### ISSUE TITLE
Freeze the search bar on scroll

### ISSUE THREAD

**Issue by Bobbicus** [cloudskew/cloudskew#10]
**Is your feature request related to a problem? Please describe.**
When you scroll down the icons list if you want to search you have to scroll back to the top to get the search bar.

**Describe the solution you'd like**
Would be great if the search bar remained frozen and usable as you scroll. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mithunshanbhag** [comment]
Good suggestion. Added this to our active backlog.

**Comment by mithunshanbhag** [comment]
Search bar is now frozen at the top of the icon palette. 
Fix pushed to production. 
Closing this issue now. Please reactivate if you're observing any errors/issues.

![sticky-search](https://user-images.githubusercontent.com/2327905/83975068-46768f00-a90f-11ea-9b7b-984bbc0a4899.gif)
