### ISSUE TITLE
Requesting Jenkins Icon

### ISSUE THREAD

**Issue by schottsfired** [cloudskew/cloudskew#100]
**What icon (or icon set) would you like to be included in cloudskew?**
Jenkins, from https://jenkins.io

**Which area/domain would these icons fall under?**
Ecosystem

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://www.dropbox.com/s/q5wxwsyu39ihwd4/icon-jenkins.svg?dl=0

Thanks

**Comment by mithunshanbhag** [comment]
Good idea. Will get this added.

**Comment by mithunshanbhag** [comment]
Icon will be available under the 'ecosystem' section. 

![image](https://user-images.githubusercontent.com/2327905/86005822-bec60100-ba32-11ea-8793-5ecfd939ed13.png)

Change will be pushed to production in a day or two.

**Comment by schottsfired** [comment]
Thanks!

**Comment by mithunshanbhag** [comment]
Changes pushed to production.

**Comment by schottsfired** [comment]
I see it! 👏 thanks again.

![image](https://user-images.githubusercontent.com/11740869/86035711-c5d91900-ba0a-11ea-9ebd-01b9d47cd3f7.png)
