### ISSUE TITLE
Requesting Salesforce Icon

### ISSUE THREAD

**Issue by susumuf** [cloudskew/cloudskew#103]
**What icon (or icon set) would you like to be included in cloudskew?**
Salesforce, Mulesoft logo from https://brandfolder.com/salesforce

**Which area/domain would these icons fall under?**
Ecosystem or somewhere

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://brandfolder.com/salesforce

**Comment by mithunshanbhag** [comment]
Added. Available now under the 'ecosystem' section

![image](https://user-images.githubusercontent.com/2327905/86002157-97b90080-ba2d-11ea-8061-533a4fec9fd9.png)

Will be pushed two production in a day or two.

**Comment by mithunshanbhag** [comment]
Changes pushed to production.
