### ISSUE TITLE
Requesting AWS Group Icons

### ISSUE THREAD

**Issue by philof** [cloudskew/cloudskew#104]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the AWS Group icons (cloud, vpc, corporate data center, etc) to be included.

**Which area/domain would these icons fall under?**
E.g. AWS groups.

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Would be great if you could point us to a download link for these icons.
https://aws.amazon.com/architecture/icons/ Assets -> SVG

**Comment by mithunshanbhag** [comment]
Thanks for reporting this issue. 

Issue #9 is tracking the work for 'group' entities: VPCs/VNETs, availability zones/sets, resource groups etc etc.

Closing this, since this work will be tracked under #9.
