### ISSUE TITLE
Haskell programming language

### ISSUE THREAD

**Issue by wraithm** [cloudskew/cloudskew#106]
**What icon (or icon set) would you like to be included in cloudskew?**
I'd like the Haskell (haskell.org) icon to be included

**Which area/domain would these icons fall under?**
Programming language

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://evenmere.org/~bts/haskell-logo/logo-0.svg

(referenced from: https://wiki.haskell.org/Haskell_logos)

Though, I kind of prefer the purple Haskell logo that's on haskell.org, but I couldn't find a suitable svg. The banner on the front page is an svg, but it has "Haskell" as the wording: https://www.haskell.org/img/haskell-logo.svg

This could be edited perhaps?

**Comment by mithunshanbhag** [comment]
The official Haskell icon has now been added.

![image](https://user-images.githubusercontent.com/2327905/89304084-a7f67800-d68a-11ea-9f29-e672c1745745.png)

This update will be released to production in 24 hours.

**Comment by mithunshanbhag** [comment]
Fix is now in production.
