### ISSUE TITLE
Go official logo

### ISSUE THREAD

**Issue by ddymko** [cloudskew/cloudskew#107]
**What icon (or icon set) would you like to be included in cloudskew?**
Cloudskew already has the Go Gopher but I am wondering if there would be any interest in updating this to the official Go logo?

https://blog.golang.org/go-brand

**Which area/domain would these icons fall under?**
Programming languages 

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://blog.golang.org/go-brand

They offer assets here https://golang.org/s/logos which have svg

**Comment by mithunshanbhag** [comment]
Ah, I wasn't aware of the new logo. Thanks for opening the issue. Will get it fixed.

**Comment by mithunshanbhag** [comment]
The icon has been updated.

![image](https://user-images.githubusercontent.com/2327905/86004336-c8e70000-ba30-11ea-9875-8fb7db1f3032.png)

Change will be pushed to production in a day or two.

**Comment by ddymko** [comment]
Awesome! Thanks!

**Comment by mithunshanbhag** [comment]
Changes pushed to production.
