### ISSUE TITLE
Requesting ClickHouse icon

### ISSUE THREAD

**Issue by t-bzhan** [cloudskew/cloudskew#110]
**What icon (or icon set) would you like to be included in cloudskew?**
Would like the ClickHouse icon to be included.

**Which area/domain would these icons fall under?**
databases

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://github.com/ClickHouse/ClickHouse/blob/master/website/images/logo.svg

**Additional details**
NA

**Comment by mithunshanbhag** [comment]
Icon now available under the 'ecosystem' section.

![image](https://user-images.githubusercontent.com/2327905/86004241-a05f0600-ba30-11ea-9426-1506b434db10.png)


Changes will be pushed to production in a day or two.

**Comment by mithunshanbhag** [comment]
Changes pushed to production.

**Comment by t-bzhan** [comment]
Works like a charm, thanks a lot.
