### ISSUE TITLE
Apache Kafka icon

### ISSUE THREAD

**Issue by faris789** [cloudskew/cloudskew#112]
**What icon (or icon set) would you like to be included?**
Apache Kafka

**Which area/domain does this fall under?**
Along with other **Apache** projects

**Where can these icons be downloaded from?** 

https://upload.wikimedia.org/wikipedia/commons/0/0a/Apache_kafka-icon.svg

**Comment by mithunshanbhag** [comment]
Apache Kafka icon has now been added under the `Ecosystem` section. This update will be available in production in a couple of hours.

![image](https://user-images.githubusercontent.com/2327905/87377674-bda3e080-c5a9-11ea-8275-664177f9e451.png)
