### ISSUE TITLE
Can't upload two different images with the same name

### ISSUE THREAD

**Issue by LikoV2** [cloudskew/cloudskew#113]
**Describe the bug**
If you upload an image, then upload a different one with the same name, the first one is displayed.

**To Reproduce**
1. Upload a custom image named "DNS.png" for example.
2. In your computer, delete the image or replace it with a different one but with the same name.
3. Upload the new image named "DNS.png".
4. The first image is displayed, not the new one.

**Expected behavior**
The second image should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/34651209/86748664-f0475980-c03c-11ea-951e-ae9043c0fa7a.png)
![image](https://user-images.githubusercontent.com/34651209/86748738-fd644880-c03c-11ea-948e-20333f05c536.png)

**Desktop (please complete the following information):**
 - Chrome Version 83.0.4103.116 (Build officiel) (64 bits)
 - OS: Windows10

**Comment by mithunshanbhag** [comment]
Fix has now been checked in (currently in the pre-production environment and will be released to production in about 24 hours).

**Comment by mithunshanbhag** [comment]
Fix is now in production.
