### ISSUE TITLE
PHP icon

### ISSUE THREAD

**Issue by ben-burns** [cloudskew/cloudskew#114]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the PHP icon to be included

**Which area/domain would these icons fall under?**
Programming

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.svg

**Comment by mithunshanbhag** [comment]
Added the PHP icon under the `programming` category. Fix will be pushed to production in a couple of hours. 

![image](https://user-images.githubusercontent.com/2327905/87312366-13db3a00-c53e-11ea-8c08-f5cd03d69b9d.png)
