### ISSUE TITLE
Kubernetes icon includes a stray character "b"

### ISSUE THREAD

**Issue by peterj** [cloudskew/cloudskew#115]
**Describe the bug**
Kubernetes icon contains a stray 'b' character

**To Reproduce**
1. Click the Kubernetes icon under CNCF
2. Add another shape over the icon to reveal the stray character in the icon (see image)

![Screen Shot 2020-07-11 at 4 14 05 PM](https://user-images.githubusercontent.com/11080940/87235534-b2766800-c391-11ea-9f62-2531c68f0870.png)

**Comment by mithunshanbhag** [comment]
Thanks for reporting this issue. The icon has now been updated and the fix will be available in production in a few hours.

![image](https://user-images.githubusercontent.com/2327905/87309612-78949580-c53a-11ea-8cb9-639cb9cacfb8.png)

Context: The stray 'b' character was from an [older version](https://github.com/cncf/artwork/commit/11394169c874e3d77f76e26bc6a71d8cca79d300#diff-dede1c6a1b38d58defefa1f791231553) of CNCF's official kubernetes icon. Looks like they have now [updated/fixed the icon recently](https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg).
