### ISSUE TITLE
Can't zoom in/out using MacOS trackpad

### ISSUE THREAD

**Issue by peterj** [cloudskew/cloudskew#116]
**Is your feature request related to a problem? Please describe.**
Zoom in/out on the canvas doesn't work when using the MacOS trackpad gesture.

**Comment by mithunshanbhag** [comment]
The following shortcuts should work for zooming in/out. 

1. Click anywhere on the diagram canvas (middle pane).
2. Use any of these shortcuts
   - Ctrl + mousewheel up/down
   - Ctrl + trackpad scroll up/down

**Comment by mithunshanbhag** [comment]
The available keyboard shortcuts are now documented [here](https://www.cloudskew.com/docs/keyboard-shortcuts.html).

Closing this issue.
