### ISSUE TITLE
Refresh Azure icons

### ISSUE THREAD

**Issue by mithunshanbhag** [cloudskew/cloudskew#117]
The latest set of Azure icons has been made available by microsoft ([link](https://docs.microsoft.com/en-us/azure/architecture/icons/)). CloudSkew needs to refresh its icon set accordingly.

**Comment by mrrsm** [comment]
Would this also bring all of the Azure services up to date including ones not currently there?

**Comment by jesseloudon** [comment]
Yes pls, you read my mind @mithunshanbhag

**Comment by mithunshanbhag** [comment]
> Would this also bring all of the Azure services up to date including ones not currently there?

@mrrsm: Yes, it will. Are you finding any azure icons missing currently?

**Comment by mrrsm** [comment]
> @mrrsm: Yes, it will. Are you finding any azure icons missing currently?  

I couldn't find the azure cache for redis icon

**Comment by mithunshanbhag** [comment]
Noted. Will add this while updating the icon set.

**Comment by mithunshanbhag** [comment]
Azure icons have been updated (to latest available version). 

![image](https://user-images.githubusercontent.com/2327905/89197126-e166af00-d5c8-11ea-9a22-7ae86aba0da4.png)

Icon for `Azure Cache for Redis` has now been added

![image](https://user-images.githubusercontent.com/2327905/89197208-fe9b7d80-d5c8-11ea-88ff-408c71cdd4c2.png)
