### ISSUE TITLE
Allow greater control over connector paths

### ISSUE THREAD

**Issue by mrrsm** [cloudskew/cloudskew#118]
Currently when adding a connector the lines can take suboptimal paths.  For example going through other items or merging with another connector.

I'd like to be able to control the placement of the connector against the bounding box of the item it's connecting to.  I would also like to be able to manipulate the line itself so I can make sure it doesn't interfere with anything else on my diagram.

Currently I have to move groups of objects around and put them in odd positions in order to get those lines to look reasonable.

**Comment by mithunshanbhag** [comment]
related: #83

**Comment by mrrsm** [comment]
Definitely a dupe. My quick scan over the open issues missed that one. Feel free to close it and track in the other issue if that workflow is better for you.

**Comment by mithunshanbhag** [comment]
Thanks @mrrsm for confirming. We'll use #83 to track this issue. Closing this one as dupe.
