### ISSUE TITLE
Possibility to import Azure reference architecture

### ISSUE THREAD

**Issue by msajid** [cloudskew/cloudskew#12]
Starting a diagram from scratch is a time-consuming job. it would be good to start with a reference architecture and then adjust to taste and requirement.

**Comment by mithunshanbhag** [comment]
Good point @msajid. 

Currently it is indeed possible to create new diagrams from existing templates. It's just that we only have two existing templates right now, but will be adding more over time. 

![image](https://user-images.githubusercontent.com/2327905/71319311-a47afb80-24c2-11ea-8a8e-36b6dfe45bd0.png)
 
Folks, please feel free to pitch in with comments, suggestions, ideas here.

**Comment by mithunshanbhag** [comment]
Given our [current roadmap](https://github.com/cloudskew/cloudskew#planned-features-calendar), there are no plans in the interim to support this. 

Closing this issue for now, will reactivate if/when we have capacity to add support.
