### ISSUE TITLE
collaborative design

### ISSUE THREAD

**Issue by AllieUbisse** [cloudskew/cloudskew#122]
**Is your feature request related to a problem? Please describe.**
sharing with edit rights, I'm working remotely with my colleague and we can he can not edit<br>
![image](https://user-images.githubusercontent.com/67786379/92503474-99f3c400-f201-11ea-9b23-4c651de915a0.png)

**Describe the solution you'd like**
Please add the can *Create Link(Edit mode)*

**Comment by mithunshanbhag** [comment]
Dupe of #60.
