### ISSUE TITLE
Request to Include Subnet and RDP Icons.

### ISSUE THREAD

**Issue by Sheshgiriv** [cloudskew/cloudskew#126]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the Subnet Icon to be included.
* I'd like the RDP Icon to be included.

**Which area/domain would these icons fall under?**
E.g. 
Subnet - Vnets or Virutal Networks
RDP - Remote Desktop Programming.
**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Would be great if you could point us to a download link for these icons.
Don't really have the download link.

**Comment by mithunshanbhag** [comment]
1. Generic icon for remote desktop added. Please note that Microsoft has not made available any official RDP icons.

![image](https://user-images.githubusercontent.com/2327905/97850462-14305880-1d1a-11eb-859b-6d86f6d5e333.png)

2. There are no official icons for subnets. However with issue #9, there are plans to represent subnets with box shapes.
