### ISSUE TITLE
Allow creating nested diagrams 

### ISSUE THREAD

**Issue by msajid** [cloudskew/cloudskew#13]
Sometimes diagrams become so big that it gets difficult to understand the high-level context. 
Nested diagrams can have click-able regions that expand and become detailed or open another diagram if clicked. check c4model fo reference.

**Comment by mithunshanbhag** [comment]
This is a good suggestion, will look into c4model at bit more closely.

However, given our [current roadmap](https://github.com/cloudskew/cloudskew#planned-features-calendar), there are no plans in the interim to support this. 

Closing this issue for now, will reactivate if/when we have capacity to add c4model support.
