### ISSUE TITLE
Onprem Server Infrastructure icons

### ISSUE THREAD

**Issue by pattsche1337** [cloudskew/cloudskew#130]
**What icon (or icon set) would you like to be included in cloudskew?**
* I'd like the legacy Microsoft Server icon set (Exchange, Database, Fileserver, Active Directory, etc.) to be included.

**Which area/domain would these icons fall under?**
Don't really know. Legacy on-prem systems (Server, ADDS, etc) to display migration to Azure, AWS, etc.

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
No idea at the moment. Included into Visio. I will follow this up.

**Comment by mithunshanbhag** [comment]
Added a bunch of generic icons related to networking, servers, files and active directory ([see release notes](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.42-preview)).
