### ISSUE TITLE
[Resolved] App not starting up anymore

### ISSUE THREAD

**Issue by TarekSalha** [cloudskew/cloudskew#136]
![image](https://user-images.githubusercontent.com/25264670/100323804-9254e780-2fc6-11eb-936c-4fb92352f884.png)

when starting the app (I am not a new user, thus it is not the problem of 24th of november) I receive the error "Unable to fetch user profile"

After showing the message, I get redirected to the home page https://www.cloudskew.com/

I am typically logging in using github login using this profile.

**Comment by mithunshanbhag** [comment]
Hi @TarekSalha: Thanks for reporting this. Things should be back to normal now. Can you please try reloading the page?

Investigation Notes:. The CloudSkew API was non-responsive and had to be restarted manually. Weirdly, this outage unexpectedly did not trigger our automated health-check alert (I'll be investigating that).

**Comment by TarekSalha** [comment]
Yup, works again 😉
Just to be curious: what service exactly are you using to perform health checks?

Von: Mithun Shanbhag <notifications@github.com>
Gesendet: Donnerstag, 26. November 2020 10:01
An: cloudskew/cloudskew <cloudskew@noreply.github.com>
Cc: Salha, Tarek <tsalha@ceteris.ag>; Mention <mention@noreply.github.com>
Betreff: Re: [cloudskew/cloudskew] App not starting up anymore (#136)


Hi @TarekSalha<https://github.com/TarekSalha>: Thanks for reporting this. Things should be back to normal now. Can you please try reloading the page?

Investigation Notes:. The CloudSkew API was non-responsive and had to be restarted manually. Weirdly, this outage unexpectedly did not trigger our automated health-check alert (I'll be investigating that).

**Comment by mithunshanbhag** [comment]
> Just to be curious: what service exactly are you using to perform health checks?

For now, just using simple metrics-based alerts (azure monitor). Some details [here](https://www.cloudskew.com/about/cloudskew-architecture.html#incident-management).
