### ISSUE TITLE
GCP and AWS Cloud Icons

### ISSUE THREAD

**Issue by Sheshgiriv** [cloudskew/cloudskew#141]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* GCP Cloud Icon
* AWS Cloud Icon.

**Which area/domain would these icons fall under?**
Cloud Service Providers

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
GCP Cloud Icon can be viewed by accessing  cloud.google.com
AWS Cloud Icon can be viewed by accessing https://aws.amazon.com/console/

**Additional details**
Please provide individual cloud icons for GCP and AWS just like the way it is there for Azure.

**Comment by mithunshanbhag** [comment]
Hi @Sheshgiriv, 

The icons for GCP and AWS already exist in CloudSkew.

![image](https://user-images.githubusercontent.com/2327905/107197283-b480d200-6a19-11eb-943c-0f4544e836cb.png)
