### ISSUE TITLE
Unable to Fetch Profile

### ISSUE THREAD

**Issue by asherthussain** [cloudskew/cloudskew#146]
**Describe the bug**
I signed up with my github account, but getting following error as depicted:

![image](https://user-images.githubusercontent.com/24833903/128232005-ca8490e0-6660-40df-84d0-c6102700791f.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]
 - OS: [e.g. windows10, macOS]

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment]
Hi @asherthussain,

I'm unable to reproduce this issue. The app loads fine for me.

Can you please try clearing your browser cache completely and reloading the app?

If the issue, still persists, please let me know. Also please let me know if you're observing any errors in the browser console.
