### ISSUE TITLE
Unable to Fetch Profile

### ISSUE THREAD

**Issue by asherthussain** [cloudskew/cloudskew#147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24833903/129519800-9aa9d884-1543-4bed-b6c6-964da65f5a5a.png)

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]
 - OS: [e.g. windows10, macOS]

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment]
Hi @asherthussain,

I'm unable to reproduce this issue. The app loads fine for me.

Can you please try clearing your browser cache completely and reloading the app?

If the issue, still persists, please let me know. Also please let me know if you're observing any errors in the browser console.
