### ISSUE TITLE
Can't load properly

### ISSUE THREAD

**Issue by akin2love** [cloudskew/cloudskew#149]
**Describe the bug**
Dear who in charge

It was happened to me same issue #132 .
So I delete several icon group, refresh page and copy some icon group.
But coping procedure was not  completed properly.
Finally I can't load my diagram.

Could you please check it out.
Regards, 

**To Reproduce**

**Expected behavior**

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]
 - OS: [e.g. windows10, macOS]

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment]
Hi @akin2love,

Apologies for the bad experience with CloudSkew.
Can you please send me the diagram URL so I can take a look?
If possible, can you also export the diagram to JSON and send it too?
You can email me at support@cloudskew.com if you don't wish to reveal this information here on github.

Thanks,
-Mithun

**Comment by mithunshanbhag** [comment]
**Update**: I've just pushed a fix to resolve the following user-reported issues: 
* fast mouse movements while dragging/resizing/moving shapes
* diagram freezes

Affected diagrams should auto-heal on page load (and even if your issue isn't resolved, the telemetry data will move us closer to a diagnosis).

**Note**: To load the latest/non-cached version of the app, go to http://app.cloudskew.com and press:
* CTRL + SHIFT + R (on windows/linux)
* CMD + SHIFT + R (on mac)
