### ISSUE TITLE
Improved connectors: curved corners + jumps

### ISSUE THREAD

**Issue by JasonBSteele** [cloudskew/cloudskew#15]
I prefer to have curved corners on my elbow connectors. Not only does it look better (IMO) but it also shows the direction of flow when connectors join/overlap each other to reach the same destination icon.

**Comment by mithunshanbhag** [comment]
Thanks for the pointing this out @JasonBSteele. 

Currently, curves/beziers are limited to curved connectors only. However let me look at enabling curved corners for the elbow connectors as well. 

Regarding overlapping connectors, that's already on the radar. Plan is to enable a connector to 'jump' over the other. 

![image](https://user-images.githubusercontent.com/2327905/71374854-43e2e000-25e2-11ea-9754-dc892132a316.png)

**Comment by JasonBSteele** [comment]
Yes the jumps are great. However I also like to "join" the connectors so that several are on top of each other as they head for an icon, so the jump logic would have to be clever enough not to try jumping when they share the same space.

**Comment by mithunshanbhag** [comment]
Support for curved corners is now enabled. The fix is currently in pre-production environment. After testing it'll be pushed to production (in a day or two). 

![image](https://user-images.githubusercontent.com/2327905/84034553-1cc57280-a9b8-11ea-844c-5e841d2a6779.png)
