### ISSUE TITLE
Elbow connectors connect to the wrong spot when page is refreshed

### ISSUE THREAD

**Issue by brtknr** [cloudskew/cloudskew#150]
**Describe the bug**
When the app is refreshed, the elbow connecters which were connected to the left dot of an icon move to the bottom for example making the allow go in a route not drawn when it is saved.

**Comment by mithunshanbhag** [comment]
Hi @brtknr: This is a known issue with elbow connectors. Unfortunately, the fix is non-trivial and might also break backward compatibility with existing diagrams. Looking into this.

**Comment by brtknr** [comment]
Whats the workaround? Do you recommend a different connector? Why is the elbow connector the default one if its broken?

**Comment by mithunshanbhag** [comment]
Unfortunately, no workarounds exist for this issue. 
Curved connector and line connectors do not encounter this issue. 

**Background**: The elbow connectors use an "aggressive" routing strategy to bypass existing shapes/text on the canvas. While the user can re-route the elbow connector, it accidentally defaults to the aggressive routing strategy on page refreshes (hence the bug).

**Comment by brtknr** [comment]
Thanks for looking into it. Please default to curved connectors until the issue is fixed at least (e.g. when you drag from the point of an icon to another one).

**Comment by mithunshanbhag** [comment]
Update: You can now attach connectors to:
* a specific dock on the symbol. OR
* the symbol itself.

The former will always stay attached to the specific dock, while the latter will dynamically route itself for the shortest path.

Note: This will only work for newer symbols loaded on the diagram canvas. Existing symbols (already on the canvas) will not be affected by this change.

![GIF 12-7-2021 5-16-57 PM](https://user-images.githubusercontent.com/2327905/145025548-2bbeb48e-058f-412e-a62a-e1123f1135d0.gif)
