### ISSUE TITLE
Scala logo

### ISSUE THREAD

**Issue by qboileau** [cloudskew/cloudskew#153]
**What icon (or icon set) would you like to be included in cloudskew?**
I'd like the Scala spiral logo to be included

**Which area/domain would these icons fall under?**
Programming

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://raw.githubusercontent.com/scala/scala-lang/main/resources/img/scala-spiral.svg (not centered)

**Additional details**
Svg logo is not centered like this [png](https://github.com/scala/scala-lang/blob/main/resources/img/scala-spiral2.png) that is better

**Comment by mithunshanbhag** [comment]
Hi @qboileau: Thanks for opening this issue. I'll get the centered SVG added. 

In the meanwhile, as a workaround, you can import any PNG/JPG file into the diagram canvas as shown below.
![image](https://user-images.githubusercontent.com/2327905/150524149-6afacd7c-7c04-4bb9-ae0b-31e099bb8535.png)

**Comment by mithunshanbhag** [comment]
The Scala icon has now been added. 
The change will be pushed to production in a few hours.

![image](https://user-images.githubusercontent.com/2327905/151796899-99e47821-1b15-440b-b769-318e0e5fc39c.png)
