### ISSUE TITLE
Diagram controls and updates not working after a certain action occured

### ISSUE THREAD

**Issue by Devin-Licastro** [cloudskew/cloudskew#158]
Spent hours finishing a diagram, was putting on the final touches when everything completely broke. Things I've noticed:
- Most of my changes will no longer save
- Dragging and dropping a few pixels sends things to the other side of the screen
- All keyboard shortcuts stopped functioning
- I cant draw arrows anymore
- Things disappear and reappear

To troubleshoot I've tried new browsers, new computers etc, nothing helps. 

I really can't bare the thought of staring this diagram over, is there any trick I can do? 
Can any dev look at my diagram in the database and fix whatever got corrupted or something? 

My account is devin@atiom.app and diagram link: https://app.cloudskew.com/editor/60b2f391-f416-42b9-9804-6c48fed9f126

**Comment by mithunshanbhag** [comment]
@Devin-Licastro: Sorry to hear that. 

You can do a page refresh (F5 in browser) to force a diagram validation and fixups (for known issues like disappearing connectors etc).

If the issue still persists after that, please let me know. You can export the diagram as json and mail it to support@cloudskew.com. We can take a look at it.

**Comment by Devin-Licastro** [comment]
Thanks for the quick response, the refresh unfortunately did not fix the issue so I've emailed you the JSON as requested. 
Much appreciated!

**Comment by Devin-Licastro** [comment]
The support staff helped fix the issue in my diagram super quickly and were very helpful, thanks a lot! Closing the issue
