### ISSUE TITLE
Expandable canvas

### ISSUE THREAD

**Issue by JasonBSteele** [cloudskew/cloudskew#18]
The canvas size is currently fixed, can it be made to automatically expand?

IMO the best way is to allow it to continually grow when drag and dropping an icon of the edge of the canvas. It stops growing when the icon is dropped

Another way is to grow it a fixed amount when an icon is dropped on the edge.

**Comment by mithunshanbhag** [comment]
Currently all diagram canvas sizes are 900px x 500px in landscape mode. 

While currently, it is possible to zoom in/out of a diagram, it is not possible to change the diagram's size/dimensions or change the diagram's orientation (to portrait mode). 

This was done for a couple of reasons: 
1: Having static size/dimensions and orientation make printing & exporting (to image) a lot easier. 
2: The plan was to enable custom dimensions as a premium/paid feature for teams & enterprises. 

However, if there is enough user demand for this feature, I will definitely consider adding it in the free tier.

**Comment by mithunshanbhag** [comment]
CloudSkew now supports infinite canvases. You can now draw arbitrarily large, multi-page diagrams!
https://github.com/cloudskew/cloudskew/releases/tag/v0.1.20-preview

Closing this issue now.
