### ISSUE TITLE
Various UI issues

### ISSUE THREAD

**Issue by Costin-hcl** [cloudskew/cloudskew#19]
**Describe the bug**
Please check attached PDF

**To Reproduce**
[Cloudskew feedback.pdf](https://github.com/cloudskew/cloudskew/files/3998086/Cloudskew.feedback.pdf)

**Comment by mithunshanbhag** [comment]
Hi @Costin-hcl, thank you very much for all the feedback. Really appreciate it! 

I'll go over all of these and open new issues to track each UI issue separately.

**Comment by mithunshanbhag** [comment]
Closing this since all the individual issues listed by @Costin-hcl are:
* being tracked by other active github issues OR
* have been resolved/fixed.
