### ISSUE TITLE
need icons from Microsoft Office and PowerBI

### ISSUE THREAD

**Issue by mithunshanbhag** [cloudskew/cloudskew#2]
**What icon (or icon set) would you like to be included in cloudskew?**
Icons for Microsoft Office and PowerBI:

- [ ] Outlook
- [ ] OneDrive
- [ ] Word
- [ ] Excel
- [ ] PowerPoint
- [ ] OneNote
- [ ] Skype
- [ ] Teams
- [ ] PowerBI

**Which area/domain would these icons fall under?**
Office productivity tools

**Where can these icons be downloaded from?**
Not sure

**Additional details**
NA

**Comment by mithunshanbhag** [comment]
Merging issue #33 into this one.

**Comment by luizwalnei** [comment]
Certainly Power BI

**Comment by mithunshanbhag** [comment]
Icons added.

![image](https://user-images.githubusercontent.com/2327905/89365437-3e11b900-d6f2-11ea-971e-bc875c48e651.png)
