### ISSUE TITLE
Power BI Icon/logo would be great

### ISSUE THREAD

**Issue by rudgr** [cloudskew/cloudskew#33]
**What icon (or icon set) would you like to be included in cloudskew?**
I'd like the Power BI icon set (word, powerpoint, excel etc) to be included.

**Which area/domain would these icons fall under?**
reporting

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Would be great if you could point us to a download link for these icons.

**Additional details**
Add any other details about the feature request here.

**Comment by mithunshanbhag** [comment]
Merging this with issue #2 (need icons from Microsoft Office and PowerBI)
