### ISSUE TITLE
Do not force login to use app

### ISSUE THREAD

**Issue by radumg** [cloudskew/cloudskew#38]
**Is your feature request related to a problem? Please describe.**
Forced login through social provider before playing with the app at all.

**Describe the solution you'd like**
Make people log in when saving a diagram or at a point after some usage.

**Describe alternatives you've considered**
We use draw.io that has Azure icons - requires no sign-up or log in.

**Additional context**
There's no about page and zero details on who's hosting this etc, so up-front requirement of social account details does NOT build trust.

**Comment by mithunshanbhag** [comment]
Good points @radumg. 

I just haven't gotten around to the putting the `about` and `privacy policy` pages etc (been a bit overwhelmed just keeping up with the feature requests, bug reports etc). Will do so soon (created #39 to explicitly track this). 

Currently diagrams are being auto-saved, which requires users to be logged in. Auto-save was a convenience feature requested by many of the initial test users. 

Regarding the "login only when saving diagram"..... will have to think about it. Will require significant rearchitecting unfortunately. 

In any event, I appreciate the feedback and will seriously look into improving the experience.

**Comment by mithunshanbhag** [comment]
Unfortunately will have to resolve this as `won't fix`. 

For better or for worse, user authentication is core to the CloudSkew user experience (personal diagram repository, auto-save etc). 

The amount of refactoring needed is non-trivial.
