### ISSUE TITLE
Canvas not expanding to leverage the full monitor resolution

### ISSUE THREAD

**Issue by ManojG1978** [cloudskew/cloudskew#41]
**Canvas not expanding to leverage the full monitor resolution**
Please see the screenshot. I have dual monitors. Not sure why the canvas is getting restricted to a certain resolution on the 23 inch monitor
![CanvasBug](https://user-images.githubusercontent.com/22010412/72896559-0ccd2f00-3d46-11ea-8944-415ca66e97b0.jpg)

**Comment by mithunshanbhag** [comment]
Fixed this issue. The diagram canvas will now span across the entire monitor width. 

![image](https://user-images.githubusercontent.com/2327905/80710254-2c75af80-8b0c-11ea-9e87-0de3684fc4ca.png)
