### ISSUE TITLE
Unable to export & print

### ISSUE THREAD

**Issue by xchello** [cloudskew/cloudskew#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]
 - OS: [e.g. windows10, macOS]

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment]
Hi @xchello: thanks for raising this issue. It's fixed now. You should be able to print & export the diagram now.
Closing this issue. Please feel free to reactivate if issue persists.

**Comment by xchello** [comment]
Thanks!

Op 27 jan. 2020 11:52 schreef Mithun Shanbhag <notifications@github.com>:

Hi @xchello<https://github.com/xchello>: thanks for raising this issue. It's fixed now. You should be able to print & export the diagram now.
Closing this issue. Please feel free to reactivate if issue persists.
