### ISSUE TITLE
Unlimited Canvas

### ISSUE THREAD

**Issue by bcosden** [cloudskew/cloudskew#43]
Canvas should be unlimited in multiple directions. Similar to Microsoft Whiteboard app but for symbols. Can be used for quick diagramming with customers.

**Comment by mithunshanbhag** [comment]
CloudSkew now supports infinite canvases. You can now draw arbitrarily large, multi-page diagrams!
https://github.com/cloudskew/cloudskew/releases/tag/v0.1.20-preview

Closing this issue now.
