### ISSUE TITLE
export the diagram as a json template file

### ISSUE THREAD

**Issue by BelRarr** [cloudskew/cloudskew#48]
**Is your feature request related to a problem? Please describe.**
having this ability would allow me to create a base template and then start every other diagramming project from it.

**Describe the solution you'd like**
export the current diagram as a json file would allow me to import it later as a base template for another diagram.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mithunshanbhag** [comment]
Update: I'm currently working on a feature to allows users to save an existing diagram as a reusable template. Users can then create new diagrams from these templates with big chunks already pre-filled (e.g. VPC/VNET configs). 

Fingers-crossed, it should be released to production early next week.

**Comment by mithunshanbhag** [comment]
This feature has now been released to production. Full [details here](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.23-preview).

PS: Please note that the reusable diagram templates are stored on the cloudskew server itself (along with your diagrams).
