### ISSUE TITLE
import a previously exported diagram

### ISSUE THREAD

**Issue by BelRarr** [cloudskew/cloudskew#49]
**Is your feature request related to a problem? Please describe.**
Following on request #48, I would like to load a diagram from a json file. This would allow to have a base template for other diagrams.

**Describe the solution you'd like**
I would like to be able to load the json of the previously exported template and see the diagram being displayed on the canvas surface.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mithunshanbhag** [comment]
Update: I'm currently working on a feature to allows users to save an existing diagram as a reusable template. Users can then create new diagrams from these templates with big chunks already pre-filled (e.g. VPC/VNET configs). 

Fingers-crossed, it should be released to production early next week.

**Comment by mithunshanbhag** [comment]
This feature has now been released to production. Full [details here](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.23-preview).
