### ISSUE TITLE
need new icons for programming languages and frameworks

### ISSUE THREAD

**Issue by mithunshanbhag** [cloudskew/cloudskew#5]
**What icon (or icon set) would you like to be included in cloudskew?**
* Various programming languages: C#, typescript, python, java, golang etc
* Various frameworks: .net, angular, node, reactjs, django etc
* Various associated package managers: nuget, npm, pip etc

**Which area/domain would these icons fall under?**
programming languages, frameworks

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Not sure

**Additional details**
N/A

**Comment by prahaladbelavadi** [comment]
I normally use Javascript, Node, Angular, Typescript, Ionic, Markdown and Git.

Webpack, gulp, yarn are also possibilities that people might likely use

**Comment by mithunshanbhag** [comment]
Added the following icons for 'programming languages and frameworks' category:

Languages: 
- [x] c#
- [x] go
- [x] java
- [x] javascript
- [x] kotlin
- [x] python
- [x] ruby
- [x] swift
- [x] typescript

Frameworks & Libraries:
- [x] angular
- [x] django
- [x] dotnetcore
- [x] expressjs
- [x] nodejs
- [x] rails.svg
- [x] reactjs.svg
- [x] vuejs.svg

![image](https://user-images.githubusercontent.com/2327905/72621227-df0f7100-3966-11ea-813e-3b08fb0d28b7.png)
