### ISSUE TITLE
import an ARM template

### ISSUE THREAD

**Issue by BelRarr** [cloudskew/cloudskew#50]
**Is your feature request related to a problem? Please describe.**
We use to deploy our Azure infrastructures as ARM templates. It would be interesting to be able to import an ARM template (json file) and see the diagram displayed on the canvas surface.

**Describe the solution you'd like**
As described above

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mithunshanbhag** [comment]
Hi @BelRarr, 

At present, there are no plans for CloudSkew to generate diagrams from ARM templates (not a lot of user demand for this feature).

However, an existing VSCode extension can generate diagrams from ARM templates: https://marketplace.visualstudio.com/items?itemName=bencoleman.armview 

Hope this helps with your user scenario.

**Comment by BelRarr** [comment]
Thanks for the reply, Mithun.

Yes, I was aware of this extension. I just thought it would be nice to have this feature integrated into CloudSkew. But I understand that it won’t be unless driven by user demand.

Best regards,

Tidjani Belmansour, Ph.D. | Azure MVP
http://espacenuagic.com<http://espacenuagic.com/> | https://dev.to/tidjani | @tidjani_b<https://twitter.com/tidjani_b>

[X]

Le 16 mars 2020 à 10:11, Mithun Shanbhag <notifications@github.com> a écrit :

﻿

Hi @BelRarr<https://github.com/BelRarr>,

At present, there are no plans for CloudSkew to generate diagrams from ARM templates (not a lot of user demand for this feature).

However, an existing VSCode extension can generate diagrams from ARM templates: https://marketplace.visualstudio.com/items?itemName=bencoleman.armview

Hope this helps with your user scenario.
