### ISSUE TITLE
compare two diagrams and generate a delta between them

### ISSUE THREAD

**Issue by BelRarr** [cloudskew/cloudskew#52]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but rather to a need. we would like to be able to compare two diagrams and generate a delta between these two.

**Describe the solution you'd like**
As part of our mission, we help customers use the cloud in a proper manner. For that matter, it happens that we evaluate their current cloud infrastructure and propose a proper one (i.e. more secure, more reliable, more cost-effective). Then, we usually modify the IaC scripts (provided that they deployed their infrastructure as code) to match the updated design. This is where such functionality would be very useful. It could help us import the two diagrams (their current one and the one we propose) and cloudskew would generate a delta script to go from the current one to the proposed one. We could then use the proposed feature #51 to export the delta as an ARM template that could be deployed to move the infrastructure from the current state to the desired one.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mithunshanbhag** [comment]
This is a good feature suggestion. 

However: 
1. unfortunately, the amount of work here involved is non-trivial (and is predicated on the success of proposed feature #51).
2. no other cloudskew users have requested this feature.

So, will have to resolve this one as a `won't fix`.
