### ISSUE TITLE
Add networking icons

### ISSUE THREAD

**Issue by e-minguez** [cloudskew/cloudskew#54]
**What icon (or icon set) would you like to be included in cloudskew?**
* I'd like general networking icons to be included (routers, switches, wifi APs, etc.)

**Which area/domain would these icons fall under?**
Networking

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
I have no idea, sorry

**Additional details**
Cool tool! :)

**Comment by mithunshanbhag** [comment]
Added a couple of icons related to networking. They are under the `Generic Resources` category and can be easily accessed by entering the search terms `network` or `networking`.

![image](https://user-images.githubusercontent.com/2327905/89644942-796cdd00-d8d6-11ea-85a3-f8a92fc0badc.png)

The change has been pushed to pre-production environment and will be released to production in a couple of hours.
