### ISSUE TITLE
Add PowerShell icon under programming

### ISSUE THREAD

**Issue by ChendrayanV** [cloudskew/cloudskew#56]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* Add PowerShell icon in Programming

**Which area/domain would these icons fall under?**
E.g. Programming

**Comment by mithunshanbhag** [comment]
Added. Should be available in production in a couple of minutes. 

![image](https://user-images.githubusercontent.com/2327905/75351808-bd42cb80-58ce-11ea-8067-4458327558ca.png)

![image](https://user-images.githubusercontent.com/2327905/75351839-c7fd6080-58ce-11ea-841e-89e44e34fb93.png)
