### ISSUE TITLE
Wishlist: icons for Svelte JS, Rust and Rocket, Elixir and Phoenix. Hashicorp Vault and Packer, and Ansible.

### ISSUE THREAD

**Issue by joelparkerhenderson** [cloudskew/cloudskew#57]
**What icon (or icon set) would you like to be included in cloudskew?**

* Svelte JS (akin to Vue)
* Rust (language) and Rocket (framework)
* Elixir (language) and Phoenix (framework)
* Hashicorp Vault and Packer (both akin to Terraform)
* Ansible (akin to Terraform)

**Comment by mithunshanbhag** [comment]
Added: https://github.com/cloudskew/cloudskew/releases/tag/v0.1.19-preview

PS: Could not find an icon for `Rocket`, so excluding it.
