### ISSUE TITLE
Power BI icon set

### ISSUE THREAD

**Issue by Oddjobe** [cloudskew/cloudskew#58]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
 I'd like the Power BI icon set (Power BI Desktop,Power BI Embedded, Power BI Mobile, Power BI Service, Power BI Gateway, Power BI Dataflow, Power BI Report) to be included.

**Which area/domain would these icons fall under?**
Analytics

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Would be great if you could point us to a download link for these icons.
Couldn't find any

**Additional details**
Add any other details about the feature request here.

**Comment by mithunshanbhag** [comment]
Unfortunately the requested icons haven't been made publicly available by Microsoft. So, at present time, nothing further can be done from CloudSkew's end. Should they become available at some point in the future, I'll add them in the app.

PS: The Power platform icons however are now available in CloudSkew (see issue #69).
