### ISSUE TITLE
Export image in SVG format

### ISSUE THREAD

**Issue by nigelpage** [cloudskew/cloudskew#59]
SVG is a much more useful format for images, enabling adjustments to be made after export and utilised in all modern tools.

Provide option for 'Export as SVG'.

No viable alternatives.

Images can be utilised in web pages, presentations, documents, etc... Images also compress very well in SVG format.

**Comment by TarekSalha** [comment]
agreed, this would be very useful

**Comment by mithunshanbhag** [comment]
Export to SVG has now been enabled ([see release note](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.49-preview)).
