### ISSUE TITLE
Grouping and Ungrouping do not work.

### ISSUE THREAD

**Issue by prasunsrivastava** [cloudskew/cloudskew#61]
**Describe the bug**
The context menu (right-click inside canvas) contains menu items for group and ungroup under the `Grouping` head. However, even after selecting multiple items, I cannot reach the group or ungroup menus. The menu just disappears.

**To Reproduce**
1. Go to any diagram.
2. Select a few items on your diagram.
3. Right click to get the context menu.
4. Go to Grouping Sub-Menu.
5. Try to get to group or ungroup. The innermost menu will disappear.

**Expected behavior**
When I try clicking on the group or subgroup menu, it should not disappear and allow me to group or ungroup objects. Please see the video in the screenshot section. 

**Screenshots**
https://www.loom.com/share/3ddc84c2b7eb4cf593b60a028268adea

**Errors in browser console**
```
ERROR TypeError: Cannot read property 'focus' of null
    at end (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.toggleAnimation (main-es2015.3f76f80c7960f31d8316.js:1)
    at ww.<anonymous> (main-es2015.3f76f80c7960f31d8316.js:1)
    at ww.notify (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.trigger (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.triggerBeforeOpen (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.openMenu (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.afterCloseMenu (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.clickHandler (main-es2015.3f76f80c7960f31d8316.js:1)
    at e.moverHandler (main-es2015.3f76f80c7960f31d8316.js:1)
Ke @ main-es2015.3f76f80c7960f31d8316.js:1
handleError @ main-es2015.3f76f80c7960f31d8316.js:1
next @ main-es2015.3f76f80c7960f31d8316.js:1
n @ main-es2015.3f76f80c7960f31d8316.js:1
__tryOrUnsub @ main-es2015.3f76f80c7960f31d8316.js:1
next @ main-es2015.3f76f80c7960f31d8316.js:1
_next @ main-es2015.3f76f80c7960f31d8316.js:1
next @ main-es2015.3f76f80c7960f31d8316.js:1
next @ main-es2015.3f76f80c7960f31d8316.js:1
emit @ main-es2015.3f76f80c7960f31d8316.js:1
(anonymous) @ main-es2015.3f76f80c7960f31d8316.js:1
invoke @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
run @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
runOutsideAngular @ main-es2015.3f76f80c7960f31d8316.js:1
onHandleError @ main-es2015.3f76f80c7960f31d8316.js:1
handleError @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
runTask @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
invokeTask @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
y @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
k @ polyfills-es2015.fd917e7c3ed57f282ee5.js:1
```

**Desktop (please complete the following information):**
 - Browser - Chrome
 - OS: Ubuntu 16.04

**Comment by mithunshanbhag** [comment]
Fix pushed to production. Please reactivate if you see this issue re-occurring.

![GIF 6-2-2020 1-01-01 PM](https://user-images.githubusercontent.com/2327905/83492864-8aadfd80-a4d1-11ea-8c46-fda9934826a6.gif)
