### ISSUE TITLE
To run Offfline

### ISSUE THREAD

**Issue by deenamanick** [cloudskew/cloudskew#62]
Hi,

is it possible to use this application in Offline or standalone application ? 

Regards,
Deena

**Comment by mithunshanbhag** [comment]
Hi Deena,

Unfortunately, at present time, there are no plans to create an offline/desktop version of CloudSkew. 

However, for organizations, there will be an enterprise version of cloudskew coming later in the year (with features such as choose-your-own-storage, bring-your-own-encryption-keys, sign-in-with-company-credentials, collaborative-editing-with-rbac etc).
