### ISSUE TITLE
Octopus Deploy Icons

### ISSUE THREAD

**Issue by maxinfet** [cloudskew/cloudskew#65]
**What icon (or icon set) would you like to be included in cloudskew?**
I would like the icons for Octopus Deploy

**Which area/domain would these icons fall under?**
deployments/orchestration

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Not sure, I think the install of Octopus Deploy would have them for the server component. https://octopus.com/downloads

**Additional details**

**Comment by mithunshanbhag** [comment]
Octopus deploy icon is now available under the `ecosystem` section in the icon palette.

![image](https://user-images.githubusercontent.com/2327905/83348569-a25b7980-a34b-11ea-981b-c68bc1f39bc9.png)
