### ISSUE TITLE
Power Platform icon

### ISSUE THREAD

**Issue by eBerdnA** [cloudskew/cloudskew#69]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the Power Platform icon set (Power Apps, Power Automate etc.) to be included.

**Which area/domain would these icons fall under?**
As #58 already requested Power BI icons maybe it is a good idea to introduce a new category like e.g. "Power Platform".

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
I could only find a download which provides stencils for Visio which contains Power Apps stencils.
https://gallery.technet.microsoft.com/Collection-of-Integration-e6a3f4d0
Don't know whether this helps.

**Additional details**
Would be highly appreciated if these icons would be available in the future.

**Comment by mithunshanbhag** [comment]
Power platform icons are now available under the 'ecosystem' tab. 

![image](https://user-images.githubusercontent.com/2327905/83520381-3b7cc280-a4fb-11ea-80b5-283ace6eb2ca.png)
