### ISSUE TITLE
need icons from various cloud computing projects

### ISSUE THREAD

**Issue by mithunshanbhag** [cloudskew/cloudskew#7]
**What icon (or icon set) would you like to be included in cloudskew?**

- [x] ~MongoDB~
- [ ] HAProxy
- [X] ~Elastic~
- [x] Heroku
- [x] Netlify
- [ ] DigitalOcean
- [x] Hashicorp
- [x] DataDog
- [ ] Sumologic

**Which area/domain would these icons fall under?**
Various. Need to re-categorize.

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
TBD.

**Additional details**
N/A.

**Comment by subbujois** [comment]
Can you please add Redhat Openshift, RHEL, Fuse and Apache Camel
