### ISSUE TITLE
Request for Alibaba Cloud icons (icon set provided)

### ISSUE THREAD

**Issue by claytonchew** [cloudskew/cloudskew#70]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the Alibaba Cloud icon set to be included.

**Which area/domain would these icons fall under?**
* Elastic Computing
* Networking
* Storage & CDN
* Security
* Database
* Domains & Websites
* Application Service
* Artificial Intelligence
* Big Data Basic
* Big Data Analysis & Visualization
* Big Data Application
* Communication
* Monitoring & Management
* Middleware
* IoT
* Analysis & Search
* Media Services
* ApsaraMobile
* Dedicated Cloud

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Download here: https://drive.google.com/open?id=1DiRK1ydTzxFhNCP8Ks0A70NYkQWYjvfa

**Comment by mithunshanbhag** [comment]
Hi @claytonchew, thanks for the link. Is this the official icon set for Alibaba cloud? [Their website ](https://www.alibabacloud.com/help/doc-detail/67830.htm) does not show the same google-drive link, hence was curious.

**Comment by claytonchew** [comment]
Hi @mithunshanbhag, the icons were painfully extracted from the website by me, hence the link, since Alibaba Cloud does not provide official vectorised icons for download. Recently the icon set were updated, giving orange colour schemes instead of blue and some minor iterations, but there are not widely adopted yet throughout their platform with inconsistency. Majority of the platform still referencing the old blue icon set.

**Comment by mithunshanbhag** [comment]
Hi @claytonchew: Thanks, this is good to know! I'll start incorporating your icons into the app now. Should be available in production by Wednesday EOD. 

PS: Will definitely credit you on the release notes! Thanks for all the hard work on this. Highly appreciated 😃

**Comment by mithunshanbhag** [comment]
Alibaba Cloud icons are now available in the app! Please see the [release notes](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.22-preview) for details.
