### ISSUE TITLE
Blazor, WASM and Github Actions Icon

### ISSUE THREAD

**Issue by indcoder** [cloudskew/cloudskew#71]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
Please include Blazor and Github actions
**Which area/domain would these icons fall under?**
Blazor in  Programming
WASM in Programming
Github Actions in Ecosystem

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Sorry, googled extensively but could not come with any links to the official .svg for any of them. [Perhaps this exposed how awful may be I'm at searching :-) ] WIll pursue this on Twitter and update this if anything comes up

**Additional details**
Add any other details about the feature request here.

**Comment by mithunshanbhag** [comment]
Update:

1. **WASM**: Official SVG icon available. Will be adding this soon.

2. **Blazor, Github actions**: Official SVG icons unavailable. PNGs are available, but they'll rasterize (will pixelate when expanded). So will be unable to add these icons to CloudSkew. As a workaround, users can upload PNGs/JPGs as custom images.

    ![image](https://user-images.githubusercontent.com/2327905/89549117-88478700-d825-11ea-897a-e23812d04efd.png)

**Comment by indcoder** [comment]
Thanks @mithunshanbhag . Thats what I had done with both Blazor and GitHub actions on our Architecture diagram. Let me follow up with those teams regarding their SVGs.
