### ISSUE TITLE
Add Kubernetes Icons

### ISSUE THREAD

**Issue by neboduus** [cloudskew/cloudskew#72]
**Is your feature request related to a problem? Please describe.**
Kubernetes objects icons missing

**Describe the solution you'd like**
Just insert them from here https://github.com/kubernetes/community/tree/master/icons

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mithunshanbhag** [comment]
Hi @neboduus, 

Kubernetes icons are already available in the app. You simply need to enable them from the `user preferences & settings menu`. 
![image](https://user-images.githubusercontent.com/2327905/80223146-83d7d380-8665-11ea-8deb-a3eda78b5455.png)

After enabling, they'll show up in the icon palette. 
![image](https://user-images.githubusercontent.com/2327905/80222991-4bd09080-8665-11ea-9d86-6b87168bf542.png)

Closing this issue now. But please feel free to reactivate if I missed anything....

**Comment by neboduus** [comment]
you're right dude. sorry, I run too fast xD
