### ISSUE TITLE
Need option to preserve aspect ratio while resizing icons

### ISSUE THREAD

**Issue by dNsl9r** [cloudskew/cloudskew#74]
**Is your feature request related to a problem? Please describe.**
When adding an Icon (e.g. Cosmos DB) I often need to resize it. Easiest way is clicking the edge and resizing it while holding the mouse button down. Works good! But the aspect ratio will change when you are not 100000 concentrated 😀 

**Describe the solution you'd like**
I'd love to see it the way it works in Photoshop: Resizing always keeps the aspect ratio, when doing a resize with pressing the **Shift Key ** the aspect ratio is not considered.

Would be a nice feature 👍

**Comment by mithunshanbhag** [comment]
Perhaps best to add a 'preserve aspect ratio' checkbox in the properties window.

**Comment by dNsl9r** [comment]
Depends - as I am working a lot with Office 365 and Adobe Products pressing a key while resizing would definitely fit my requirements.
In Office tools for example holding the Shift Key does the job.
Adding a checkbox would work but would not be the best option in my opinion.

**Comment by mithunshanbhag** [comment]
related #55.

**Comment by mithunshanbhag** [comment]
You can now preserve a symbol's aspect ratio while resizing it ([see release notes for details](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.43-preview)).
