### ISSUE TITLE
Database Table attribute icons

### ISSUE THREAD

**Issue by ArionMiles** [cloudskew/cloudskew#76]
**What icon (or icon set) would you like to be included in cloudskew?**
I'd like a database table attribute icon much like the one below to be available. 
![db_table_attributes](https://user-images.githubusercontent.com/13501594/81902382-a9f5f100-95dd-11ea-9f08-a8e4f78c7e67.png)

**Which area/domain would these icons fall under?**
Databases

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Unfortunately I don't have a proper source file. I believe it's available on draw.io. If you search for `attributes` on draw.io you can see this icon.

**Comment by mithunshanbhag** [comment]
Thanks for opening this issue @ArionMiles. Will try to add these by early next week.

**Comment by mithunshanbhag** [comment]
Added icons for tables, table attributes (available under the `Generic Resources` category. 

Change is currently in pre-production and will be released to prod in a couple of hours.

![image](https://user-images.githubusercontent.com/2327905/89543328-6696d180-d81e-11ea-9289-099b0168ca34.png)
