### ISSUE TITLE
Pin search bar at the top

### ISSUE THREAD

**Issue by SathyaBhat** [cloudskew/cloudskew#77]
**Is your feature request related to a problem? Please describe.**
The search bar is a nice feature but it doesn't stay at top when when scrolling. this is especially painful when you've scrolled half way down and need to scroll all the way back up to search

**Describe the solution you'd like**
If the search bar is pinned and not scrolled over, it would be good.

**Describe alternatives you've considered**
No alternatives exist

**Additional context**
![image](https://user-images.githubusercontent.com/25424/83045724-a5eeb800-a04e-11ea-8080-23cb3fd413f7.png)

**Comment by mithunshanbhag** [comment]
Dupe of #10.

**Comment by mithunshanbhag** [comment]
Search bar is now frozen at the top of the icon palette. 
Fix pushed to production. 

![sticky-search](https://user-images.githubusercontent.com/2327905/83975068-46768f00-a90f-11ea-9b7b-984bbc0a4899.gif)
