### ISSUE TITLE
Every item/object should have a text label feature

### ISSUE THREAD

**Issue by SathyaBhat** [cloudskew/cloudskew#78]
**Is your feature request related to a problem? Please describe.**
Every object/item figure must have a text label to describe what the object is supposed to be.  

**Describe the solution you'd like**
A text property in the existing properties would be nice

![image](https://user-images.githubusercontent.com/25424/83046025-0f6ec680-a04f-11ea-9098-9e6d6e6fa096.png)

![image](https://user-images.githubusercontent.com/25424/83046060-1dbce280-a04f-11ea-841b-1694bc2ae582.png)

**Describe alternatives you've considered**
An alternative is to add the text next to every item/object but thats painful

**Comment by mithunshanbhag** [comment]
This already exists, right? To add text to any symbol you can simply:
* double click on it and start typing OR
* select symbol, click F2 and start typing. 

See example here: https://www.youtube.com/watch?v=d-lIrtaFUe0

Other notes: 
* The symbol's text can be dragged/repositioned as needed. 
* To format/style a symbol's text, select the symbol and then edit the text properties from the properties pane (right hand side pane).

**Comment by SathyaBhat** [comment]
Thanks - I didn't think to double click and try. Follow up questions: I can't seem to drag/reposition the text, the drag icon moves the entire symbol. How do I drag just the text?

also I notice the text property on the object is shown after I add the text - if the text property was there since start it would be much more obvious

**Comment by mithunshanbhag** [comment]
You will have to resize the text borders until you see a four-pronged arrow. See this gif below:
![GIF](https://user-images.githubusercontent.com/2327905/83112060-35de4180-a0e3-11ea-9891-2bfae828ef29.gif)

> I notice the text property on the object is shown after I add the text
Unfortunately this is because, the text property object does not exist in memory until it is initialized (via double-click or F2). Only then can it be styled/formatted. Let me see if I can make experience better in the coming sprints (by pre-initializing the text or something).

**Comment by SathyaBhat** [comment]
I dont seem to get the text borders itself

![2020-05-29 12-44-45](https://user-images.githubusercontent.com/25424/83250647-262d2e80-a1b1-11ea-8b08-a201036919c5.gif)

**Comment by mithunshanbhag** [comment]
Text borders only exist for icons, arrows/connectors, geometric shapes and custom images. 

They don't exist for text shapes (like the one in your gif above). 

If you're just attempting to reposition text around some icons, then best to use the double-click/F2 annotation.

Let me know if you're still experiencing issues, I can jump on a zoom call to help you out.

**Comment by SathyaBhat** [comment]
problem was that I was using an old diagram which didn't have support for the draggable text
thanks for your time @mithunshanbhag 👍
