### ISSUE TITLE
Hasura Icon

### ISSUE THREAD

**Issue by ArionMiles** [cloudskew/cloudskew#84]
**What icon (or icon set) would you like to be included in cloudskew?**
Hasura icon (hasura.io)

**Which area/domain would these icons fall under?**
Ecosystem

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
Would be great if you could point us to a download link for these icons.
I've included their SVG here.
[hasura.zip](https://github.com/cloudskew/cloudskew/files/4735087/hasura.zip)

**Comment by ArionMiles** [comment]
Additionally they have an entire directory of logo and other assets which include SVGs here https://github.com/hasura/graphql-engine/tree/master/assets/brand

**Comment by mithunshanbhag** [comment]
Added the icon. 
Will be released to production in a day or two.

![hasura](https://user-images.githubusercontent.com/2327905/83998894-3b5b4780-a97f-11ea-9412-8412f1b9d6d2.gif)

**Comment by mithunshanbhag** [comment]
Changes are now live in production.
