### ISSUE TITLE
Caddy server Icon

### ISSUE THREAD

**Issue by ArionMiles** [cloudskew/cloudskew#85]
**What icon (or icon set) would you like to be included in cloudskew?**
Some examples:
* I'd like the [Caddy server](https://caddyserver.com/) logo to be included.

**Which area/domain would these icons fall under?**
Ecosystem

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://caddyserver.com/resources/images/caddy-circle-lock.svg

**Comment by mithunshanbhag** [comment]
Unfortunately, this icon will not be added for the following reasons:

1. The linked SVG file is actually loading an embedded base64 PNG (non-vectorized) using `xlink:href="data:image/png;base64`.

2. Caddy Server 2 doesn't have an official branding kit yet. 

As a workaround, caddy server icons PNG/JPG can be loaded as a custom image.
