### ISSUE TITLE
service bus topics and queue

### ISSUE THREAD

**Issue by siddheshp** [cloudskew/cloudskew#99]
**What icon (or icon set) would you like to be included in cloudskew?**
* I'd like the service bus topics and queue icon set

**Which area/domain would these icons fall under?**
Service Bus

**Where can these icons be downloaded from?** (note: only `.svg` format is supported at the moment)
https://vecta.io/symbols/28/microsoft-azure-color/57/service-bus-topics
https://symbols.getvecta.com/stencil_28/55_service-bus-queues.28fa70b9e0.svg

**Comment by mithunshanbhag** [comment]
Unfortunately, [Microsoft's official, licensed icon set for Azure](https://www.microsoft.com/en-in/download/details.aspx?id=41937) only includes icons for service bus & service bus relay. 

The icons for topics and queues are unofficial and/or lack a permissible license. 

So won't be able to add these to CloudSkew.
